project_id = "yusmekgbrimlrzoglwtg"

[functions.send-order-notification]
verify_jwt = false
 
 [functions.clickpesa-payment]
 verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
